import PageLayout from "../../components/PageLayout"

export default function Disclaimer() {

  return (

    <PageLayout
      title="Disclaimer"
      description="Legal disclaimer and usage terms for Bioinformatics Tools Hub."
    >

      <div className="max-w-4xl mx-auto space-y-8 text-slate-700 leading-relaxed">

        <section className="space-y-3">

          <h2 className="text-2xl font-semibold text-slate-900">
            General Information
          </h2>

          <p>
            The tools and information provided on <strong>Bioinformatics Tools Hub </strong>
            are intended for educational and research purposes. While efforts are
            made to ensure the accuracy and reliability of the algorithms and
            analyses provided, the website and its tools are offered without
            guarantees of correctness, completeness, or suitability for any
            specific application.
          </p>

        </section>


        <section className="space-y-3">

          <h2 className="text-xl font-semibold text-slate-900">
            Scientific and Research Use
          </h2>

          <p>
            Results generated by these tools should not be considered definitive
            scientific conclusions. Users are encouraged to validate results using
            established bioinformatics software, peer-reviewed methodologies,
            and appropriate experimental verification before relying on them in
            publications or research conclusions.
          </p>

        </section>


        <section className="space-y-3">

          <h2 className="text-xl font-semibold text-slate-900">
            No Warranty
          </h2>

          <p>
            Bioinformatics Tools Hub is provided on an “as is” and “as available”
            basis without warranties of any kind, either express or implied,
            including but not limited to the accuracy, reliability, or availability
            of the tools or information provided.
          </p>

        </section>


        <section className="space-y-3">

          <h2 className="text-xl font-semibold text-slate-900">
            Limitation of Liability
          </h2>

          <p>
            The authors and maintainers of Bioinformatics Tools Hub shall not be
            held liable for any damages, losses, or consequences arising from the
            use of the tools or information provided on this website. Use of the
            platform is entirely at the user's own risk.
          </p>

        </section>


        <section className="space-y-3">

          <h2 className="text-xl font-semibold text-slate-900">
            Data Privacy
          </h2>

          <p>
            Most sequence analysis tools on this platform operate entirely within
            the user's browser. Unless explicitly stated otherwise, biological
            sequences entered into the tools are not transmitted to external
            servers.
          </p>

        </section>


        <section className="space-y-3">

          <h2 className="text-xl font-semibold text-slate-900">
            External Resources
          </h2>

          <p>
            Some tools reference publicly available biological databases or
            external scientific resources. Bioinformatics Tools Hub does not
            control or guarantee the accuracy or availability of third-party
            resources.
          </p>

        </section>

      </div>

    </PageLayout>

  )

}